/** @type {import("prettier").Config} */
export default {
  arrowParens: "always",
  importOrder: [
    "^vitest",
    "",
    "^@nuxt/test-utils|^@vue/test-utils",
    "^vite/(.*)$|^vite|^@vitejs/(.*)$|^@vitejs",
    "",
    "<BUILTIN_MODULES>",
    "",
    "^@vue/(.*)$|^vue/(.*)$|^vue",
    "",
    "^@nuxt/(.*)$|^@nuxt|^@nuxtjs/(.*)$|^@nuxtjs|^nuxt/(.*)$|^nuxt",
    "",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@vee-ui/(.*)$",
    "",
    "^#app|^#imports",
    "",
    "^#ui/(.*)$",
    "",
    "^@/(.*)$|^~/(.*)$",
    "",
    "^[./]",
  ],
  jsxSingleQuote: false,
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  printWidth: 80,
  proseWrap: "always",
  quoteProps: "consistent",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "all",
  useTabs: false,
};
