packages:
  - packages/**
  - turbo/tools/*

catalog:
  '@tailwindcss/vite': ^4.1.11
  eslint: ^9.30.1
  nuxt: ^3.17.6
  prettier: ^3.6.2
  tailwindcss: ^4.1.10
  typescript: ^5.8.3
  vue: ^3.5.17

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - 'sharp'
  - unrs-resolver
